/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros_rosjava_tutorial_native_node_ChatterNativeNode */

#ifndef _Included_org_ros_rosjava_tutorial_native_node_ChatterNativeNode
#define _Included_org_ros_rosjava_tutorial_native_node_ChatterNativeNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ros_rosjava_tutorial_native_node_ChatterNativeNode
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_ChatterNativeNode_execute
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

/*
 * Class:     org_ros_rosjava_tutorial_native_node_ChatterNativeNode
 * Method:    shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ros_rosjava_1tutorial_1native_1node_ChatterNativeNode_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_ros_node_NativeNodeMain */

#ifndef _Included_org_ros_node_NativeNodeMain
#define _Included_org_ros_node_NativeNodeMain
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
